# Generated by Django 6.0.3 on 2026-04-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='assigned_agent',
            field=models.CharField(max_length=100),
        ),
    ]
