# Generated by Django 6.0.3 on 2026-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_field_assigned_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldupdate',
            name='agent',
            field=models.CharField(max_length=100),
        ),
    ]
