# Generated by Django 6.0.3 on 2026-04-22 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_alter_fieldupdate_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='assigned_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
