# Generated by Django 6.0.3 on 2026-04-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_alter_field_assigned_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
